name: deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'client/**'
      - 'server/**'
      - '.docker/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow

#    - name: Get go dependencies and build server
#      working-directory: server
#      run: |
#        go get -v -t -d . 
#        ./build

#    - name: Get npm dependencies and build Client
#      working-directory: client
#      run: | 
#        npm install
#        npm run build

    - name: Build the base image
      run: docker build -f ./.docker/base/Dockerfile -t jcbird1012/neko:base .
  
    - name: Push the Docker images
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push jcbird1012/neko:base
    
    - name: Build the latest firefox image
      run: docker build -f ./.docker/firefox/Dockerfile -t jcbird1012/neko:latest .

    - name: Build the latest chromium image
      run: docker build -f ./.docker/chromium/Dockerfile -t jcbird1012/neko:chromium .

    - name: Build the latest ungoogled-chromium image
      run: docker build -f ./.docker/ungoogled-chromium/Dockerfile -t jcbird1012/neko:ungoogled-chromium .

    - name: Push the Docker images
      run: | 
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push jcbird1012/neko:latest
        docker push jcbird1012/neko:chromium
        docker push jcbird1012/neko:ungoogled-chromium
